[build]
  base = "frontend/"
  publish = "dist/"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[context.production.environment]
  VUE_APP_API_LOCATION="https://disinfoapi.politiwatch.org/"