[build]
  base = "frontend/"
  publish = "dist/"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[context.production.environment]
  VUE_APP_API_LOCATION="https://disinfoapi.politiwatch.org/"