---
apiVersion: v1
kind: Service
metadata:
  name: trollsearch-mongodb-service
  labels:
    name: trollsearch-mongodb-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trollsearch-mongodb
spec:
  selector:
    matchLabels:
      role: mongo
      environment: prod
  serviceName: trollsearch-mongodb-service
  template:
    metadata:
      labels:
        role: mongo
        environment: prod
    spec:
      containers:
      - name: mongo
        image: mongo
        command:
          - mongod
          - '--bind_ip'
          - '0.0.0.0'
        ports:
          - containerPort: 27017
        resources:
          requests:
            memory: 2Gi
          limits:
            memory: 6Gi
        volumeMounts:
          - name: trollsearch-mongodb-disk
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: trollsearch-mongodb-disk
      spec:
        storageClassName: default
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: trollsearch-backend
spec:
  selector:
    matchLabels:
      app: trollsearch-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: trollsearch-backend
    spec:
      tolerations:
      - key: kubernetes.azure.com/scalesetpriority
        value: spot
        effect: NoSchedule
      containers:
      - name: trollsearch-backend
        image: politiwatch/trollsearch:latest
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: MONGODB_HOST
          value: "mongodb://trollsearch-mongodb-0.trollsearch-mongodb-service:27017/trollsearch"
---
apiVersion: v1
kind: Service
metadata:
  name: trollsearch-backend-service  
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: trollsearch-backend
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: trollsearch-backend-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: disinfoapi.politiwatch.org
    http:
      paths:
      - backend:
          serviceName: trollsearch-backend-service
          servicePort: 80
        path: /